name: 02 - Workflow events

on: 
  pull_request:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Show the trigger
      run: echo "This was triggered by ${{ github.event_name}}"

